---
- name: Create Folder {{ heplify_path }}
  file:
    path: "{{ heplify_path }}"
    recurse: yes
    state: directory

- name: Download HepLify
  get_url:
    url: "{{ heplify_url }}"
    dest: "{{ heplify_path }}/heplify"
    mode: 0740

- name: Copy service template
  template:
    src: heplify.service.j2
    dest: /etc/systemd/system/heplify.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable service heplify, and not touch the state
  service:
    name: heplify
    enabled: yes

- name: Start service heplify, if not started
  service:
    name: heplify
    state: started
