---
- name: Create directory {{ heplify_path }}
  file:
    path: "{{ heplify_path }}"
    recurse: true
    state: directory

- name: Download heplify
  get_url:
    url: "{{ heplify_url }}"
    dest: "{{ heplify_path }}/heplify"
    mode: 0750

- name: Copy service template
  template:
    src: heplify.service.j2
    dest: /etc/systemd/system/heplify.service
    owner: root
    group: root
    mode: 0644
  notify: restart heplify

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable and start heplify service
  systemd:
    name: heplify
    state: started
    enabled: true
